### ISSUE TITLE
Cannot find the changed/new RDMA files

### ISSUE THREAD

**Issue by johnxusjtu** [kaixili/Tensorflow-RDMA#1]
Hi Kaixi,
     I'm now involved in a distributed tensorflow project and hope to improve the communication performance by utilizing the RDMA technology. So your work is precious for us. However, I could not find the changed files through the path "src/core/..." provided in the rdma.pdf file. Seems it's a generated directory by Bazel.
     Could show me how to find the changed files? Thanks a lot!

**Comment by kaixili** [comment]
Hi JohnXZG,
Distributed communication of tensorflow is in git submodule grpc. All files i modify is in grpc. when you transfer grpc to rdma version, you can modify Bazel build file: grpc.BUILD to use grpc rdma version.

**Comment by johnxusjtu** [comment]
Thanks for your timely reply, Kaixi! 
Unfortunately, I cannot recover the git submodule grpc you mentioned, through the src/grpc.git directory. Is it possible that I can reach the grpc repo where your rdma code works? Thanks again!

**Comment by kaixili** [comment]
$git clone localpathtogrpc/grpc.git 
by the way , the grpc and tenserflow version i changed is old, i dont know whether it can work well in new version.

**Comment by johnxusjtu** [comment]
Thanks Kaixi! It works now. Hope I can make improvements based on your excellent work.
